"""Keyword dictionaries used by the quick content threat model."""

THREAT_KEYWORDS = {
    "verify your account": 4,
    "confirm your identity": 4,
    "update billing": 4,
    "account suspended": 5,
    "urgent action": 4,
    "security alert": 3,
    "unusual activity": 3,
    "login credentials": 5,
    "enter password": 4,
    "reset password": 3,
    "one time password": 3,
    "bank account": 4,
    "credit card": 4,
    "social security": 5,
    "ssn": 5,
    "wire transfer": 4,
    "claim your prize": 3,
    "lottery winner": 3,
    "act now": 3,
    "click here": 2,
    "confirm password": 4,
    "verify now": 4,
    "signin": 2,
    "sign in": 2,
    "password": 2,
    "verify": 2,
    "urgent": 2,
    "suspended": 3,
}

SAFE_KEYWORDS = {
    "privacy policy": 3,
    "terms of service": 3,
    "cookie policy": 2,
    "about us": 2,
    "contact us": 2,
    "documentation": 3,
    "help center": 2,
    "all rights reserved": 2,
    "official website": 2,
    "developer": 1,
    "support": 1,
    "faq": 1,
    "community": 1,
    "status page": 2,
    "careers": 1,
    "blog": 1,
}

URGENCY_KEYWORDS = {
    "urgent": 2,
    "urgent action": 3,
    "immediately": 2,
    "act now": 3,
    "expires today": 3,
    "limited time": 2,
    "suspended": 2,
    "warning": 2,
}

CREDENTIAL_KEYWORDS = {
    "login": 2,
    "sign in": 2,
    "signin": 2,
    "username": 2,
    "password": 3,
    "passcode": 2,
    "otp": 2,
    "one time password": 3,
    "security code": 2,
}

FINANCIAL_KEYWORDS = {
    "bank": 2,
    "bank account": 3,
    "credit card": 3,
    "debit card": 3,
    "routing number": 4,
    "billing": 2,
    "payment": 2,
    "invoice": 2,
    "wire transfer": 4,
}

BRAND_KEYWORDS = {
    "paypal": 3,
    "microsoft": 3,
    "office365": 3,
    "google": 3,
    "gmail": 3,
    "apple": 3,
    "amazon": 3,
    "facebook": 3,
    "instagram": 3,
    "linkedin": 3,
    "netflix": 3,
    "bank": 2,
}
