"""Keyword dictionaries used by the quick content threat model."""

THREAT_KEYWORDS = {
    "verify your account": 4,
    "confirm your identity": 4,
    "update billing": 4,
    "account suspended": 5,
    "urgent action": 4,
    "security alert": 3,
    "unusual activity": 3,
    "login credentials": 5,
    "enter password": 4,
    "reset password": 3,
    "one time password": 3,
    "bank account": 4,
    "credit card": 4,
    "social security": 5,
    "ssn": 5,
    "wire transfer": 4,
    "claim your prize": 3,
    "lottery winner": 3,
    "act now": 3,
    "click here": 2,
    "confirm password": 4,
    "verify now": 4,
    "signin": 2,
    "sign in": 2,
    "password": 2,
    "verify": 2,
    "urgent": 2,
    "suspended": 3,
}

SAFE_KEYWORDS = {
    "privacy policy": 3,
    "terms of service": 3,
    "cookie policy": 2,
    "about us": 2,
    "contact us": 2,
    "documentation": 3,
    "help center": 2,
    "all rights reserved": 2,
    "official website": 2,
    "developer": 1,
    "support": 1,
    "faq": 1,
    "community": 1,
    "status page": 2,
    "careers": 1,
    "blog": 1,
}
